create table if not exists public.profiles (
    id uuid primary key references auth.users(id) on delete cascade,
    username text unique not null check (char_length(username) between 3 and 18),
    title text not null default 'Noob',
    role text not null default 'player' check (role in ('player', 'owner')),
    tokens integer not null default 0 check (tokens >= 0),
    xp integer not null default 0 check (xp >= 0),
    level integer not null default 1 check (level >= 1),
    coins integer not null default 0 check (coins >= 0),
    streak integer not null default 0 check (streak >= 0),
    best_streak integer not null default 0 check (best_streak >= 0),
    equipped_blook jsonb not null default '{"name":"Starter Blook","icon":"⭐","rarity":"Common"}'::jsonb,
    collection jsonb not null default '[{"name":"Starter Blook","icon":"⭐","rarity":"Common"}]'::jsonb,
    stats jsonb not null default '{"gamesPlayed":0,"questionsAnswered":0,"correctAnswers":0,"coinsEarned":0,"packsOpened":0,"modes":{}}'::jsonb,
    created_at timestamptz not null default now(),
    updated_at timestamptz not null default now()
);

alter table public.profiles add column if not exists title text not null default 'Noob';
alter table public.profiles add column if not exists role text not null default 'player';
alter table public.profiles add column if not exists tokens integer not null default 0;
alter table public.profiles add column if not exists xp integer not null default 0;
alter table public.profiles add column if not exists level integer not null default 1;

create table if not exists public.chat_messages (
    id bigint generated by default as identity primary key,
    user_id uuid not null references auth.users(id) on delete cascade,
    username text not null,
    message text not null check (char_length(message) between 1 and 180),
    created_at timestamptz not null default now()
);

create table if not exists public.games (
    code text primary key check (code ~ '^[A-Z0-9]{6}$'),
    host_id uuid not null references auth.users(id) on delete cascade,
    mode text not null default 'quick',
    status text not null default 'waiting' check (status in ('waiting','playing','finished')),
    question_index integer not null default 0,
    created_at timestamptz not null default now()
);

create table if not exists public.game_players (
    game_code text not null references public.games(code) on delete cascade,
    user_id uuid not null references auth.users(id) on delete cascade,
    username text not null,
    score integer not null default 0,
    ready boolean not null default false,
    joined_at timestamptz not null default now(),
    primary key (game_code, user_id)
);

create or replace view public.leaderboard as
select username, title, tokens, xp, level
from public.profiles;

grant select on public.leaderboard to authenticated;

create or replace function public.handle_new_user()
returns trigger language plpgsql security definer set search_path = public as $$
begin
    insert into public.profiles (id, username, title, role)
    values (
        new.id,
        coalesce(new.raw_user_meta_data ->> 'username', split_part(new.email, '@', 1)),
        case when lower(new.email) = 'felipitinatorrocketleague@gmail.com' then 'Owner' else 'Noob' end,
        case when lower(new.email) = 'felipitinatorrocketleague@gmail.com' then 'owner' else 'player' end
    );
    return new;
end;
$$;

drop trigger if exists on_auth_user_created on auth.users;
create trigger on_auth_user_created after insert on auth.users
for each row execute procedure public.handle_new_user();

-- Create profiles for accounts that existed before this schema was installed.
insert into public.profiles (id, username)
select
    users.id,
    left(coalesce(users.raw_user_meta_data ->> 'username', split_part(users.email, '@', 1)), 18)
from auth.users as users
where not exists (
    select 1
    from public.profiles as profiles
    where profiles.id = users.id
);

update public.profiles
set role = 'owner', title = 'Owner'
where id = (
    select id
    from auth.users
    where email = 'felipitinatorrocketleague@gmail.com'
);

alter table public.profiles enable row level security;
alter table public.chat_messages enable row level security;
alter table public.games enable row level security;
alter table public.game_players enable row level security;

create or replace function public.is_owner()
returns boolean
language sql
security definer
set search_path = public
stable
as $$
    select exists (
        select 1 from public.profiles
        where id = auth.uid() and role = 'owner'
    );
$$;

create or replace function public.protect_profile_fields()
returns trigger
language plpgsql
security definer
set search_path = public
as $$
begin
    if not public.is_owner() then
        new.role = old.role;
        new.title = old.title;
    end if;
    return new;
end;
$$;

drop trigger if exists protect_profile_fields on public.profiles;
create trigger protect_profile_fields
before update on public.profiles
for each row execute procedure public.protect_profile_fields();

drop policy if exists "Profiles are public to authenticated users" on public.profiles;
create policy "Profiles are public to authenticated users" on public.profiles for select to authenticated using (auth.uid() = id);
drop policy if exists "Owner reads all profiles" on public.profiles;
create policy "Owner reads all profiles" on public.profiles for select to authenticated using (public.is_owner());
drop policy if exists "Users update their own profile" on public.profiles;
create policy "Users update their own profile" on public.profiles for update to authenticated using (auth.uid() = id) with check (auth.uid() = id);

drop policy if exists "Authenticated users read chat" on public.chat_messages;
create policy "Authenticated users read chat" on public.chat_messages for select to authenticated using (true);
drop policy if exists "Authenticated users send chat" on public.chat_messages;
create policy "Authenticated users send chat" on public.chat_messages for insert to authenticated with check (auth.uid() = user_id);

drop policy if exists "Authenticated users read games" on public.games;
create policy "Authenticated users read games" on public.games for select to authenticated using (true);
drop policy if exists "Authenticated users create games" on public.games;
create policy "Authenticated users create games" on public.games for insert to authenticated with check (auth.uid() = host_id);
drop policy if exists "Hosts update games" on public.games;
create policy "Hosts update games" on public.games for update to authenticated using (auth.uid() = host_id) with check (auth.uid() = host_id);
drop policy if exists "Hosts delete games" on public.games;
create policy "Hosts delete games" on public.games for delete to authenticated using (auth.uid() = host_id);

drop policy if exists "Authenticated users read players" on public.game_players;
create policy "Authenticated users read players" on public.game_players for select to authenticated using (true);
drop policy if exists "Users join as themselves" on public.game_players;
create policy "Users join as themselves" on public.game_players for insert to authenticated with check (auth.uid() = user_id);
drop policy if exists "Users update their own player row" on public.game_players;
create policy "Users update their own player row" on public.game_players for update to authenticated using (auth.uid() = user_id) with check (auth.uid() = user_id);
drop policy if exists "Users leave their own game" on public.game_players;
create policy "Users leave their own game" on public.game_players for delete to authenticated using (auth.uid() = user_id);

alter table public.chat_messages replica identity full;
alter table public.games replica identity full;
alter table public.game_players replica identity full;

-- Add tables to Realtime only when they are not already there.
do $$
begin
    if not exists (
        select 1
        from pg_publication_tables
        where pubname = 'supabase_realtime'
          and schemaname = 'public'
          and tablename = 'chat_messages'
    ) then
        alter publication supabase_realtime add table public.chat_messages;
    end if;

    if not exists (
        select 1
        from pg_publication_tables
        where pubname = 'supabase_realtime'
          and schemaname = 'public'
          and tablename = 'games'
    ) then
        alter publication supabase_realtime add table public.games;
    end if;

    if not exists (
        select 1
        from pg_publication_tables
        where pubname = 'supabase_realtime'
          and schemaname = 'public'
          and tablename = 'game_players'
    ) then
        alter publication supabase_realtime add table public.game_players;
    end if;
end $$;
